services:
  api:
    build:
      context: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/var/www/html
    depends_on:
      - db
    networks:
      - app-network

  front:
    build:
      context: ./front
    ports:
      - "5173:5173"
    volumes:
      - ./front:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    working_dir: /usr/src/app
    networks:
      - app-network

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: magazord
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
